Revert "jQuery, upgrade to 3.4.1, keep 3.2.1 on disk for older third party plugins and disable jquery-migrations while herre."
-- seems to be for later, dashboard dies with "Uncaught TypeError: e.indexOf is not a function .... "

This reverts commit 8871419f4dc81138dd3874ef754c20c457d5a5a3.