mvc:models:Interfaces - safeguard setValue('') when being called on construction (and if/ipaddr have not been created yet).
Prevents:

*** OPNsense\DHCRelay\DHCRelay migration failed from 0.0.0 to 1.0.1, check log for details

Fatal error: Uncaught InvalidArgumentException: if not an attribute of gif.1bdc715a-06bf-4212-950f-f8911a1bd8ec in /usr/local/opnsense/mvc/app/models/OPNsense/Base/FieldTypes/BaseField.php:369
Stack trace:

This surfaced after changing BaseModel to always call setValue() for non container objects without comparisong (https://github.com/opnsense/core/commit/a2ebe130b?w=1), which does seem more logical as one may bind logic to the setter, in which case the implementation is responsible for checking its own requirements.